name: Kotlin Verification CI

on:
  push:
    branches:
      - dev
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Build with Gradle
        run: ./gradlew build -x lintKotlinMain -x lintKotlinTest -x lintKotlin
      - name: Ktlint format
        run: ./gradlew formatKotlin
      - name: Ktlint check
        run: ./gradlew lintKotlin
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4.1.2
        with:
          commit_message: Apply formatting changes
          commit_user_name: TakaoBot
          branch: ${{ github.head_ref }}
      - name: Launch Test
        run: ./gradlew test
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}